In [1]:
import numpy as np
print(np.__version__)


2.2.3


In [2]:
list = [10,20,30,40,50]
arr = np.array(list)
print(arr)
print('Type: ',type(arr))


[10 20 30 40 50]
Type:  <class 'numpy.ndarray'>


In [9]:
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr1.shape)
print(arr1.size)


print(arr1[0])
print(arr1[0][1])

[[1 2 3]
 [4 5 6]]
(2, 3)
6
[1 2 3]
2


In [16]:
arr1 = np.zeros((2,3))
print(arr1)

arr1 = np.zeros((2,3),dtype=int)
print(arr1)

arr2 = np.arange(2,5)
print(arr2)

arr3 = np.arange(1,10,3)
print(arr3)


[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]]
[2 3 4]
[1 4 7]


In [19]:
arr4 = np.array([np.arange(1,10,3),np.arange(2,10,3)])
print(arr4)



[[1 4 7]
 [2 5 8]]


In [22]:
a = np.arange(1,10,3)
b = np.arange(2,10,3)

print(a+b)
print(a*b)
print(a**2)


[ 3  9 15]
[ 2 20 56]
[ 1 16 49]


In [25]:
purchases = np.array([
    [200,150,100],
    [300,250,400],
    [100,200,150],
    [500,600,550],
    [80,50,60]
])

total_spend = purchases.sum(axis=1)
print(f"Total spend: {total_spend}")

avg_spend = purchases.mean(axis=1)
print(f"Average spend: {avg_spend}")

print(avg_spend.mean())


Total spend: [ 450  950  450 1650  190]
Average spend: [150.         316.66666667 150.         550.          63.33333333]
246.0


In [27]:
# 2x + 3y = 8
# 4x + y = 10

A = np.array([[2,3],[4,1]])

B = np.array([8,10])

sol = np.linalg.solve(A,B)

print(f"x is {sol[0]} , y is {sol[1]}")



x is 2.2 , y is 1.2


In [43]:
sales = np.array([1000,1500,1200,1800,1100,1300,2400,1500,1700,1100])

print(f"Total Sales: {sales.sum()} , Average Sales: {sales.mean()} , Highest Sales: {max(sales)} , Lowest Sales: {min(sales)}")

print(sales)

for i in sales:
    if i>sales.mean():
        print(f"{i} ")

print(f"Sales higher than average {sales[sales>sales.mean()]}")

sales2 = np.array(sales * 1.1)
print(sales2)

sales.sort()
# np.sort(sales)
print(sales)




Total Sales: 14600 , Average Sales: 1460.0 , Highest Sales: 2400 , Lowest Sales: 1000
[1000 1500 1200 1800 1100 1300 2400 1500 1700 1100]
1500 
1800 
2400 
1500 
1700 
Sales higher than average [1500 1800 2400 1500 1700]
[1100. 1650. 1320. 1980. 1210. 1430. 2640. 1650. 1870. 1210.]
[1000 1100 1100 1200 1300 1500 1500 1700 1800 2400]


In [53]:
import pandas as pd

df = pd.read_csv('sales_data2.csv')
# print(df)

df.isnull()

df.fillna(0)

df.duplicated()

df.dtypes

df['Date'] = pd.to_datetime(df['Date'])
print(df)



   Order_ID       Product     Category  Quantity  Price  Total_Amount  \
0      1001        Laptop  Electronics         2    700           NaN   
1      1002  Mobile Phone  Electronics         1    500           NaN   
2      1003    Headphones  Accessories         3     50           NaN   
3      1004         Mouse  Accessories         2     20           NaN   
4      1005      Keyboard  Accessories         1     30           NaN   
5      1006       T-shirt     Clothing         4     15           NaN   
6      1007        Jacket     Clothing         1     60           NaN   
7      1008  Refrigerator  Electronics         1    900           NaN   
8      1009            TV  Electronics         2   1100           NaN   
9      1010         Shoes     Clothing         2     40           NaN   

         Date  
0  2024-02-01  
1  2024-02-02  
2  2024-02-03  
3  2024-02-04  
4  2024-02-05  
5  2024-02-06  
6  2024-02-07  
7  2024-02-08  
8  2024-02-09  
9  2024-02-10  


In [54]:
data = np.array([10,12,14,15,18,21,25,100])

Q1 = np.percentile(data,25)
# Q1 = (data * 0.25)

Q3 = np.percentile(data,75)
# Q2 = (data * 0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = data [(data < lower_bound) | (data>upper_bound)]

print("Outliers: ",outliers)



Outliers:  [100]
